### PR TITLE
Add Shipwright Operator as library

### PR DESCRIPTION
**Pull request by sayan-biswas**
Added code to run Shipwright Operator's build controller imported from upstream [Shipwright](https://github.com/shipwright-io/operator) project.

### CODE REVIEW

**Comment by sayan-biswas** [comment]
/hold

I will adding unit tests

**Review by adambkaplan — COMMENTED** [review]
My browser seems to be struggling with the number of files in this PR, so I'm going to provide comments here.

First, I recommend taking a hard look at the current Kubernetes API conventions, especially when it comes to [Optional vs. Required](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required). If a field is required, it means that a user must set a value in order for the k8s apiserver to accept it.

I think we want an experience where `spec` is a required field, but whose _values_ are optional and can be empty. Thus the following YAML is valid:

```yaml
kind: OpenShiftBuild
apiVersion: operator.openshift.io/v1alpha1
metadata:
  name: cluster
spec: {}
```

If this is encountered, the operator should set explicit default values. I think this can be done as follows:

1. Use pointers for the `Shipwright` and `SharedResource` fields on `OpenShiftBuildSpec`. Mark these as `// +optional` in the godoc and add `omitempty` to the JSON tag.
2. For `Shipwright`, make the `Build` field a pointer and mark it optional, add `omitempty` to the JSON tag.
3. For `Build`, set the `State` kubebuilder default tag to `Enabled`.
4. For `SharedResource`, set the `State` kubebuilder default tag to `Enabled`.

The controller for `OpenShiftBuild` should then take a ["late initialization"](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#controller-assigned-defaults-aka-late-initialization) approach to ensure the object is fully specified at the API level.

```yaml
spec:
  shipwright:
    build:
      state: Enabled
  shared-resources:
    state: Enabled
```

**Comment by adambkaplan** [comment]
/ok-to-test

Not sure why Konflux checks haven't run here...

**Comment by sayan-biswas** [comment]
> /ok-to-test
> 
> Not sure why Konflux checks haven't run here...

There were some issues with the CEL expression, fixed in this PR. #32 
Now, the build and unit test passed. I think we can ignore the snyk results now.

**Review by adambkaplan — APPROVED** [review]
lgtm - merging so we can iterate.

**Pull request merged**
