### PR TITLE
BUILD-1199: Bump shipwright-io/operator to Latest

### PR DESCRIPTION
**Pull request by adambkaplan**
Update shipwright-io/operator dependency to bring in the upstream fix that adds default pruner settings in the generated TetkonConfig object.

### CODE REVIEW

**Comment by sayan-biswas** [comment]
Reran EC test as logs were not available for the previous one.

**Comment by sayan-biswas** [comment]
The EC errors are due to outdated tasks.

**Comment by adambkaplan** [comment]
EC checks should not block merge of pull requests. They are meant to block release!

**Review by sayan-biswas — APPROVED** [review]

**Comment by sayan-biswas** [comment]
Merging this, EC errors not related to this. Will fix EC error in followup PRs.

**Pull request merged**
