### PR TITLE
fix: Enterprise contract

### PR DESCRIPTION
**Pull request by sayan-biswas**
Fix enterprise contract tests

### CODE REVIEW

**Comment by ramessesii2** [comment]
I see the following violation:
```

[validate] Success: false
[validate] Result: FAILURE
[validate] Violations: 1, Warnings: 1, Successes: 96
[validate] Component: openshift-builds-operator-bundle-1-1
[validate] ImageRef: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-operator-bundle@sha256:d2c565eb63eb4678af95fc5fe6134a9a75136354c39475630912d3188f8a052e
[validate] 
[validate] Results:
[validate] ✕ [Violation] tasks.required_tasks_found
[validate]   ImageRef: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-operator-bundle@sha256:d2c565eb63eb4678af95fc5fe6134a9a75136354c39475630912d3188f8a052e
[validate]   Reason: One of "prefetch-dependencies", "prefetch-dependencies-oci-ta" tasks is missing
[validate]   Title: All required tasks were included in the pipeline
[validate]   Description: Ensure that the set of required tasks are included in the PipelineRun attestation. To exclude this rule add one or
[validate]   more of "tasks.required_tasks_found:prefetch-dependencies", "tasks.required_tasks_found:prefetch-dependencies-oci-ta" to the
[validate]   `exclude` section of the policy configuration.
[validate]   Solution: Make sure all required tasks are in the build pipeline. The required task list is contained as
[validate]   xref:ec-cli:ROOT:configuration.adoc#_data_sources[data] under the key 'required-tasks'.
```
I'm wondering if it's a flake since we already excluded `prefetch` task from the violations check.

**Comment by sayan-biswas** [comment]
> I see the following violation:
> 
> ```
> 
> [validate] Success: false
> [validate] Result: FAILURE
> [validate] Violations: 1, Warnings: 1, Successes: 96
> [validate] Component: openshift-builds-operator-bundle-1-1
> [validate] ImageRef: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-operator-bundle@sha256:d2c565eb63eb4678af95fc5fe6134a9a75136354c39475630912d3188f8a052e
> [validate] 
> [validate] Results:
> [validate] ✕ [Violation] tasks.required_tasks_found
> [validate]   ImageRef: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-operator-bundle@sha256:d2c565eb63eb4678af95fc5fe6134a9a75136354c39475630912d3188f8a052e
> [validate]   Reason: One of "prefetch-dependencies", "prefetch-dependencies-oci-ta" tasks is missing
> [validate]   Title: All required tasks were included in the pipeline
> [validate]   Description: Ensure that the set of required tasks are included in the PipelineRun attestation. To exclude this rule add one or
> [validate]   more of "tasks.required_tasks_found:prefetch-dependencies", "tasks.required_tasks_found:prefetch-dependencies-oci-ta" to the
> [validate]   `exclude` section of the policy configuration.
> [validate]   Solution: Make sure all required tasks are in the build pipeline. The required task list is contained as
> [validate]   xref:ec-cli:ROOT:configuration.adoc#_data_sources[data] under the key 'required-tasks'.
> ```
> 
> I'm wondering if it's a flake since we already excluded `prefetch` task from the violations check.

This is not a flake, this message is from the previous EC Test `openshift-builds-enterprise-contract`. New one is `openshift-builds-enterprise-contract-1-1`

**Comment by ramessesii2** [comment]
ohh! I see. Thanks for clarifying.

**Pull request merged**
